{
 "title": "Nature Remo Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "serial_number", "label": "Device", "query": { "query": "label_values(serial_number)" } }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "℃" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "natureremo_temperature{serial_number=\"$serial_number\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "natureremo_humidity{serial_number=\"$serial_number\"}"
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "natureremo_illumination{serial_number=\"$serial_number\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "℃" } },
   "targets": [
    {
     "expr": "natureremo_temperature{serial_number=\"$serial_number\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "natureremo_humidity{serial_number=\"$serial_number\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "natureremo_illumination{serial_number=\"$serial_number\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}